// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockWalletService creates a new instance of MockWalletService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWalletService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWalletService {
	mock := &MockWalletService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWalletService is an autogenerated mock type for the WalletService type
type MockWalletService struct {
	mock.Mock
}

type MockWalletService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWalletService) EXPECT() *MockWalletService_Expecter {
	return &MockWalletService_Expecter{mock: &_m.Mock}
}

// Deposit provides a mock function for the type MockWalletService
func (_mock *MockWalletService) Deposit(walletID string, amount int) error {
	ret := _mock.Called(walletID, amount)

	if len(ret) == 0 {
		panic("no return value specified for Deposit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, int) error); ok {
		r0 = returnFunc(walletID, amount)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWalletService_Deposit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deposit'
type MockWalletService_Deposit_Call struct {
	*mock.Call
}

// Deposit is a helper method to define mock.On call
//   - walletID string
//   - amount int
func (_e *MockWalletService_Expecter) Deposit(walletID interface{}, amount interface{}) *MockWalletService_Deposit_Call {
	return &MockWalletService_Deposit_Call{Call: _e.mock.On("Deposit", walletID, amount)}
}

func (_c *MockWalletService_Deposit_Call) Run(run func(walletID string, amount int)) *MockWalletService_Deposit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWalletService_Deposit_Call) Return(err error) *MockWalletService_Deposit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWalletService_Deposit_Call) RunAndReturn(run func(walletID string, amount int) error) *MockWalletService_Deposit_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalance provides a mock function for the type MockWalletService
func (_mock *MockWalletService) GetBalance(walletID string) (int, error) {
	ret := _mock.Called(walletID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (int, error)); ok {
		return returnFunc(walletID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) int); ok {
		r0 = returnFunc(walletID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(walletID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWalletService_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type MockWalletService_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - walletID string
func (_e *MockWalletService_Expecter) GetBalance(walletID interface{}) *MockWalletService_GetBalance_Call {
	return &MockWalletService_GetBalance_Call{Call: _e.mock.On("GetBalance", walletID)}
}

func (_c *MockWalletService_GetBalance_Call) Run(run func(walletID string)) *MockWalletService_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWalletService_GetBalance_Call) Return(n int, err error) *MockWalletService_GetBalance_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockWalletService_GetBalance_Call) RunAndReturn(run func(walletID string) (int, error)) *MockWalletService_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// Withdraw provides a mock function for the type MockWalletService
func (_mock *MockWalletService) Withdraw(walletID string, amount int) error {
	ret := _mock.Called(walletID, amount)

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, int) error); ok {
		r0 = returnFunc(walletID, amount)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWalletService_Withdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Withdraw'
type MockWalletService_Withdraw_Call struct {
	*mock.Call
}

// Withdraw is a helper method to define mock.On call
//   - walletID string
//   - amount int
func (_e *MockWalletService_Expecter) Withdraw(walletID interface{}, amount interface{}) *MockWalletService_Withdraw_Call {
	return &MockWalletService_Withdraw_Call{Call: _e.mock.On("Withdraw", walletID, amount)}
}

func (_c *MockWalletService_Withdraw_Call) Run(run func(walletID string, amount int)) *MockWalletService_Withdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWalletService_Withdraw_Call) Return(err error) *MockWalletService_Withdraw_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWalletService_Withdraw_Call) RunAndReturn(run func(walletID string, amount int) error) *MockWalletService_Withdraw_Call {
	_c.Call.Return(run)
	return _c
}
